### ISSUE TITLE
求教创建view实现读写分离，优化mysql具体是怎么实现？

### ISSUE THREAD

**Issue by z-yz** [fankcoder/fankcoder.github.io#1]

**Comment by z-yz** [comment]
MySQL视图表应该并不能优化mysql的查询效率吧，他只是可以简化查询，从而优化代码效率

而您所说的利用view实现读写分离，应该不太对吧
我理解的view，本身没有数据，而在访问view的时候，才去select 构造数据，所以还是查询，只是简化了查询，所以效率上并没有增加

以上理解不清楚是否正确，望指教。

如果以上理解正确的话，您的操作可能反而降低了查询你性能。
理由：
因为您需要的是最近插入的5条数据，而建立的视图最长select了一天的数据，相比较下查询效率应该会降低

是否可以测试下两种方式查询的实际用时？

**Comment by z-yz** [comment]
COUNT优化
优化分页，使用下面语句代替count函数

explain select * from `table_name`;

**Comment by z-yz** [comment]
> COUNT优化
> 优化分页，使用下面语句代替count函数
> 
> explain select * from `table_name`;

这里楼主用的应该是InnoDB引擎吧，文章中可以明确标注下
MyISAM引擎的count值是直接保存在磁盘上的，select直接给出结果，很高效（当然只的是总行数，没有where条件）

**Comment by fankcoder** [comment]
@z-yz 统一回复，
1. 关于MySQL视图表，这里是用了一种取巧的方法，通过限定数据范围，提高查询速度。它的本质是一个查询结果集，现在视图原本的功能也并不常用，程序员会考虑拆分关联SQL来解决复杂查询。这里是从MySQL角度出发进行优化，如果从架构的角度，建议你选择使用缓存数据库。
2. 你可以自行尝试比较 对千万级以上的表建立小部分数据的视图表，然后在原本的千万级表分别进行查询作时间对比。需要特别说明的是，关于文中 “每2s查询最近插入的5条数据” 读写分离的用法通常会出现查询时间差问题，当时没有考虑到，这种业务情况不建议使用读写分离。
3. MyISAM引擎不需要优化总行数，没必要特别说明。
4. 提问建议直接在博客留言（需要科学上网）或发邮件，不建议开issue，issue通常用来处理博客代码问题，不处理内容。
